name: Build & Publish

on:
  push:
    tags:
      - '*.*.*.*'
  workflow_dispatch: # Allows manual trigger

jobs:
  Build:
    permissions:
      contents: write
    runs-on: windows-latest

    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Get Environment Variables
      run: |
        $tag = "${{ github.ref }}" -replace 'refs/tags/', ''
        "tag=$tag" | Out-File -Append -FilePath $Env:GITHUB_ENV
        echo $env:PROJECT_NAME - $tag
        
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 10.0.x
      
    - name: Download Dalamud Latest
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"
        
    - name: Restore Nuget Packages
      run: dotnet restore $env:PROJECT_NAME/$env:PROJECT_NAME.csproj

    - name: Build Plugin
      run: dotnet build --no-restore -c Release $env:PROJECT_NAME/$env:PROJECT_NAME.csproj -p:AssemblyVersion=${{ env.tag }} -p:FileVersion=${{ env.tag }} -p:PackageVersion=${{ env.tag }} -p:InformationalVersion=${{ env.tag }} --output .\build

    - name: Test Outputs
      run: |
        echo "---------"
        dir .\
        echo "---------"
        dir .\build
        echo "---------"
        dir .\build\$env:PROJECT_NAME
        echo "---------"
        dir .\$env:PROJECT_NAME
        echo "---------"
        dir .\$env:PROJECT_NAME\$env:PROJECT_NAME
        
    # - name: Publish Plugin
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     files: ./build/$env:PROJECT_NAME/latest.zip
    #     token: ${{ secrets.GITHUB_TOKEN }}
