name: Build & Publish

on:
  push:
    tags:
      - '*.*.*.*'

jobs:
  Build:
    permissions:
      contents: write
    runs-on: windows-latest

    env:
      PROJECT_NAME: ${{ github.repository.split('/')[1] }}
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Get Environment Variables
      run: |
        echo $env:PROJECT_NAME
        $tag = "${{ github.ref }}" -replace 'refs/tags/', ''
        "tag=$tag" | Out-File -Append -FilePath $Env:GITHUB_ENV
        
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 10.0.x
        
    - name: Restore Nuget Packages
      run: dotnet restore

    - name: Build Plugin
      run: dotnet build --no-restore -c Release $ -p:AssemblyVersion=${{ env.tag }} -p:FileVersion=${{ env.tag }} -p:PackageVersion=${{ env.tag }} -p:InformationalVersion=${{ env.tag }} --output .\build

    - name: Publish Plugin
      uses: softprops/action-gh-release@v2
      with:
        files: ./build/$env:PROJECT_NAME/latest.zip
        token: ${{ secrets.GITHUB_TOKEN }}
